### ISSUE TITLE
Display Suggestions

### ISSUE THREAD

**Issue by fjh3646** [damiankorcz/Prism-Theme#91] opened 2022-10-15 14:51 UTC
1. Hope to increase the effect of centered pictures and tables, and provide options for users to choose from. 
2. Hope to add the option to modify the display width.

**Comment by damiankorcz** [comment] 2022-12-29 17:01
Hi @fjh3646,
Since the first issue is very similar to #56 I will close this issue. As for the second issue, you can customise the width of the Readable Line Length in Style Settings ( Style Settings -> Prism Theme -> Editor -> Custom Readable Line Length (px) ).

Duplicate of #56

**Comment by damiankorcz** [comment] 2022-12-29 17:01
Duplicate of https://github.com/damiankorcz/Prism-Theme/issues/56

**Closed by damiankorcz** 2022-12-29 17:01 UTC
Labels: Feature Request

**Comment by RedKimberly** [comment] 2023-12-11 22:03
> Hi @fjh3646,
> Since the first issue is very similar to #56 I will close this issue. As for the second issue, you can customise the width of the Readable Line Length in Style Settings ( Style Settings -> Prism Theme -> Editor -> Custom Readable Line Length (px) ).

Is there another way to adjust the note width? I have it set to the max line length of 1800, but the note width is still very narrow. I am running macOS version 11.7.10 if that makes a difference.

**Comment by damiankorcz** [comment] 2023-12-12 06:04
Hi @RedKimberly,
Can't say I've ever expected the need for a larger line length but I guess you have a very high resolution screen. You can overwrite the width with a [CSS snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets):
```css
body {
    --file-line-width: 1000px !important;
}
```
Change the amount of pixels to what you want.
